/*********************************************************************
* 作者: 麦_Mike
* 时间: 20010-2-22
* 描述: 游戏事件
**********************************************************************/
/**
游戏事件申明在这里
*/
enum GAME_EVENT
{
	GAME_INIT_DONE,							//游戏初始化完毕
	VERSION_REQUEST_ING,					//版本验证中	
	VERSION_OK,								//版本验证成功
	VERSION_FAILED,							//版本验证失败
	LOGIN_OK,								//登录成功
	LOGIN_FAILED,							//登录失败
	ROLE_LIST_RETURN_EMPTY,					//角色列表返回空
	ROLE_CREATED_FAILED,					//创建角色失败
	REQUEST_SCENE_OK,						//请求场景成功
	REQUEST_SCENE_FAILED,					//请求场景失败

	START_FIT_EDIT,
	END_FIT_EDIT,
	FIT_NEW_ADDED,							//家装新添加
	UPDATE_STORAGE_UI,						//更新仓库UI
	UPDATE_BODY_UI,							//更新装备信息
	// XiaoMing Add
	NPC_DIALOG,							    //Npc对话
	CHANGE_SCENE,                           //通知切换场景
	SHOW_FITMENTINTERACT_UI,				//显示家具交互UI(环形菜单)
	ON_CLICKED_GAMEOBJ,						//点击游戏物体
	
	// 弹出
	SHOW_INVITE_DIALOG,
	// 拒绝邀请
	UNSHOW_INVITE_DIALOG,

	// 通知交易开始
	TRADE_START,
	MY_TRADE_MONEY,
	OTHER_TRADE_MONEY,
	MY_TRADE_SURE,
	OTHER_TRADE_SURE,
	TRADE_CANCEL,
	TRADE_SUCCESS,
	UPDATE_MY_TRADE,
	UPDATE_OTHER_TRADE,

	//
	ON_CLICKED_RECV_PROPERTY,//收到属性同不消息

	//
	UPDATE_NPC_UI_BY_OPT,	//更新NPC UI
	UPDATE_NPC_UI_BY_MSG,	//更新NPC UI
	NPC_CLOSE_DIALOG,

	UPDATE_PLAYER_GOLD, //更新商城EQ币

	FIRST_ENTER_FARM,	//第一次进入农场
	UPDATE_UI_FARM_DATA,//农场数据更新
	EXIT_FUNNY_FARM,	//退出农场

	UPDATE_TASK_UI,	//任务UI

	POP_FARM_SETTING, //弹出农场设置框
	
	DRAG_ITEM_UNDOED,//撤消物品拖放
	
	POP_HOME_SERVICE, //家政画面
	EXIST_PURCHASE_ITEM,//重复购买农场物品

	POP_WORK_UI,
	UPDATE_DISEASE,
	ENTER_GAME,

	UPDATE_STORAGE,
	UPDATE_FARMGOLD,	//更新农场金币
	NOTIFY_PICKAWARD,
	END_ALLPICK,
	NOTIFY_TUTSAWARD,
	CHANGE_RESOLUTION,
	CHANGE_DAYNIGHT,
	CREATEMSGBOX_SUCCESS,

	START_CHANGE_SCENE, //开始切换场景
	END_CHANGE_SCENE, //结束切换场景
	START_BUY_HOUSE, //开始买房屋
	END_BUY_HOUSE, //结束买房屋
	ADD_ALLACTION_OK,
	UPDATE_SEARCHKEY,
	UPDATE_IITDATA_UI,
	NOTIFY_FARM_ISACTIVE,
	NOTIFY_FARM_NOACTIVE,
	NOTIFY_CLOSE_SYSMSG_BOX,	// 关闭系统消息框(2011/4/29 add by hezhr)
	NOTIFY_OFFLINE_INVITE,
	OFFLINE_INVITERECORDS_SHOWlIST_UPDATE,
	DRIFTBOTTLELISTUPDATE,
	DRIFTBOTTLELIST_PAGECHANGE,
	UPDATE_FARMEQGOLD,	//更新农场EQ币

	GE_COUNT //事件个数，任何新加的事件都要放到这个前面

};

const std::string game_event[] = 
{
	"GAME_INIT_DONE",
	"VERSION_REQUEST_ING",
	"VERSION_OK",
	"VERSION_FAILED",
	"LOGIN_OK",
	"LOGIN_FAILED",

	"ROLE_LIST_RETURN_EMPTY",
	"ROLE_CREATED_FAILED",

	"REQUEST_SCENE_OK",
	"REQUEST_SCENE_FAILED",

	"START_FIT_EDIT",
	"END_FIT_EDIT",
	"FIT_NEW_ADDED",
	"UPDATE_STORAGE_UI",
	"UPDATE_BODY_UI",
	// XiaoMing Add
	"NPC_DIALOG",
	"CHANGE_SCENE",
	"SHOW_FITMENTINTERACT_UI",
	"ON_CLICKED_GAMEOBJ",
	"SHOW_INVITE_DIALOG",
	"UNSHOW_INVITE_DIALOG",

	"TRADE_START",
	"MY_TRADE_MONEY",
	"OTHER_TRADE_MONEY",
	"MY_TRADE_SURE",
	"OTHER_TRADE_SURE",
	"TRADE_CANCEL",
	"TRADE_SUCCESS",
	"UPDATE_MY_TRADE",
	"UPDATE_OTHER_TRADE",

	"ON_CLICKED_RECV_PROPERTY",

	"UPDATE_NPC_UI_BY_OPT",	//更新NPC UI"
	"UPDATE_NPC_UI_BY_MSG",	//更新NPC UI"
	"NPC_CLOSE_DIALOG",
	"UPDATE_PLAYER_GOLD",
	"FIRST_ENTER_FARM",		//第一次进入农场
	"UPDATE_UI_FARM_DATA",	//农场数据更新
	"EXIT_FUNNY_FARM",		//退出农场
	"UPDATE_TASK_UI",

	"POP_FARM_SETTING",
	"DRAG_ITEM_UNDOED",
	"POP_HOME_SERVICE",
	"EXIST_PURCHASE_ITEM",
	"POP_WORK_UI",
	"UPDATE_DISEASE",
	"ENTER_GAME",
	"UPDATE_STORAGE",
	"UPDATE_FARMGOLD",
	"NOTIFY_PICKAWARD",
	"END_ALLPICK",
	"NOTIFY_TUTSAWARD",
	"CHANGE_RESOLUTION",
	"CHANGE_DAYNIGHT",
	"CREATEMSGBOX_SUCCESS",

	"START_CHANGE_SCENE", //开始切换场景
	"END_CHANGE_SCENE", //结束切换场景
	"START_BUY_HOUSE", //开始买房屋
	"END_BUY_HOUSE", //结束买房屋
	"ADD_ALLACTION_OK",
	"UPDATE_SEARCHKEY",
	"UPDATE_IITDATA_UI",
	"NOTIFY_FARM_ISACTIVE",
	"NOTIFY_FARM_NOACTIVE",
	"NOTIFY_CLOSE_SYSMSG_BOX",	// 关闭系统消息框(2011/4/29 add by hezhr)
	"NOTIFY_OFFLINE_INVITE",
	"OFFLINE_INVITERECORDS_SHOWlIST_UPDATE",
	"DRIFTBOTTLELISTUPDATE",
	"DRIFTBOTTLELIST_PAGECHANGE",
	"UPDATE_FARMEQGOLD",
};
