/////////////////////////////////////////////////////////////////////////////
// Name:        addgroupdlg.h
// Purpose:     
// Author:      xj
// Modified by: 
// Created:     19/11/2010 10:52:19
// RCS-ID:      
// Copyright:   XJ-1
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 19/11/2010 10:52:19

#ifndef _ADDGROUPDLG_H_
#define _ADDGROUPDLG_H_


/*!
 * Includes
 */

////@begin includes
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_ADDGROUPDLG 10037
#define ID_TXT_GDIR 10039
#define ID_CHOICE 10050
#define ID_BTN_BROWSER 10049
#define ID_BTN_OK 10040
#define ID_BTN_CANCEL 10041
#define SYMBOL_ADDGROUPDLG_STYLE wxCAPTION|wxSYSTEM_MENU|wxCLOSE_BOX|wxMINIMIZE_BOX|wxTAB_TRAVERSAL
#define SYMBOL_ADDGROUPDLG_TITLE wxGetTranslation(wxString() + (wxChar) 0x589E + (wxChar) 0x52A0 + (wxChar) 0x7EC4)
#define SYMBOL_ADDGROUPDLG_IDNAME ID_ADDGROUPDLG
#define SYMBOL_ADDGROUPDLG_SIZE wxSize(400, 300)
#define SYMBOL_ADDGROUPDLG_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * AddGroupDlg class declaration
 */

class AddGroupDlg: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( AddGroupDlg )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    AddGroupDlg();
    AddGroupDlg( wxWindow* parent, wxWindowID id = SYMBOL_ADDGROUPDLG_IDNAME, const wxString& caption = SYMBOL_ADDGROUPDLG_TITLE, const wxPoint& pos = SYMBOL_ADDGROUPDLG_POSITION, const wxSize& size = SYMBOL_ADDGROUPDLG_SIZE, long style = SYMBOL_ADDGROUPDLG_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_ADDGROUPDLG_IDNAME, const wxString& caption = SYMBOL_ADDGROUPDLG_TITLE, const wxPoint& pos = SYMBOL_ADDGROUPDLG_POSITION, const wxSize& size = SYMBOL_ADDGROUPDLG_SIZE, long style = SYMBOL_ADDGROUPDLG_STYLE );

    /// Destructor
    ~AddGroupDlg();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin AddGroupDlg event handler declarations

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BTN_BROWSER
    void OnBtnBrowserClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BTN_OK
    void OnBtnOkClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BTN_CANCEL
    void OnBtnCancelClick( wxCommandEvent& event );

////@end AddGroupDlg event handler declarations

////@begin AddGroupDlg member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end AddGroupDlg member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin AddGroupDlg member variables
	wxTextCtrl* m_txtDir;
	wxChoice* m_pCmbType;
////@end AddGroupDlg member variables
};

#endif
    // _ADDGROUPDLG_H_
