/////////////////////////////////////////////////////////////////////////////
// Name:        additemdlg.h
// Purpose:     
// Author:      xj
// Modified by: 
// Created:     19/11/2010 14:32:47
// RCS-ID:      
// Copyright:   XJ-1
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 19/11/2010 14:32:47

#ifndef _ADDITEMDLG_H_
#define _ADDITEMDLG_H_

#include "ItemFilter.h"

/*!
 * Includes
 */

////@begin includes
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_ADDITEMDLG 10042
#define ID_CMB_GROUP 10043
#define ID_TXT_PREFIX 10044
#define ID_TXT_ITEMS 10045
#define ID_BTN_BDIR 10051
#define ID_BTN_BROWSER 10046
#define ID_BTN_OK 10047
#define ID_BTN_CANCEL 10048
#define ID_BTN_ADDDIR 10049
#define SYMBOL_ADDITEMDLG_STYLE wxCAPTION|wxSYSTEM_MENU|wxCLOSE_BOX|wxMINIMIZE_BOX|wxTAB_TRAVERSAL
#define SYMBOL_ADDITEMDLG_TITLE wxGetTranslation(wxString() + (wxChar) 0x589E + (wxChar) 0x52A0 + (wxChar) 0x9879)
#define SYMBOL_ADDITEMDLG_IDNAME ID_ADDITEMDLG
#define SYMBOL_ADDITEMDLG_SIZE wxSize(400, 300)
#define SYMBOL_ADDITEMDLG_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * AddItemDlg class declaration
 */

class AddItemDlg: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( AddItemDlg )
    DECLARE_EVENT_TABLE()

protected:
	ItemFilter m_itemFilter;

protected:
	void AddDir(wxString &root, wxString &dir, wxString &items);

public:
    /// Constructors
    AddItemDlg();
    AddItemDlg( wxWindow* parent, wxWindowID id = SYMBOL_ADDITEMDLG_IDNAME, const wxString& caption = SYMBOL_ADDITEMDLG_TITLE, const wxPoint& pos = SYMBOL_ADDITEMDLG_POSITION, const wxSize& size = SYMBOL_ADDITEMDLG_SIZE, long style = SYMBOL_ADDITEMDLG_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_ADDITEMDLG_IDNAME, const wxString& caption = SYMBOL_ADDITEMDLG_TITLE, const wxPoint& pos = SYMBOL_ADDITEMDLG_POSITION, const wxSize& size = SYMBOL_ADDITEMDLG_SIZE, long style = SYMBOL_ADDITEMDLG_STYLE );

    /// Destructor
    ~AddItemDlg();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin AddItemDlg event handler declarations

	/// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BTN_BDIR
	void OnBtnBdirClick( wxCommandEvent& event );

	void OnBtnAddDirClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BTN_BROWSER
    void OnBtnBrowserClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BTN_OK
    void OnBtnOkClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BTN_CANCEL
    void OnBtnCancelClick( wxCommandEvent& event );

////@end AddItemDlg event handler declarations

////@begin AddItemDlg member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end AddItemDlg member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin AddItemDlg member variables
    wxComboBox* m_cmbGroup;
    wxTextCtrl* m_txtPrefix;
    wxTextCtrl* m_txtItems;
////@end AddItemDlg member variables
};

#endif
    // _ADDITEMDLG_H_
