/////////////////////////////////////////////////////////////////////////////
// Name:        listmakerdlg.h
// Purpose:     
// Author:      xj
// Modified by: 
// Created:     16/11/2010 14:20:13
// RCS-ID:      
// Copyright:   XJ-1
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 16/11/2010 14:20:13

#ifndef _LISTMAKERDLG_H_
#define _LISTMAKERDLG_H_

#define ELEMENT_LIST "List"
#define ELEMENT_GROUP "Group"
#define ELEMENT_ITEM "Item"
#define ATTRIBUTE_DIRECTORY "Directory"
#define ATTRIBUTE_FILE "File"
#define ATTRIBUTE_CODE "Code"

#define wxELEMENT_LIST wxT("List")
#define wxELEMENT_GROUP wxT("Group")
#define wxELEMENT_ITEM wxT("Item")
#define wxATTRIBUTE_DIRECTORY wxT("Directory")
#define wxATTRIBUTE_FILE wxT("File")
#define wxATTRIBUTE_CODE wxT("Code")

/*!
 * Includes
 */

////@begin includes
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_LISTMAKERDLG 10000
#define ID_TXT_XML 10001
#define ID_TXT_DIR 10002
#define ID_BROWSER 10003
#define ID_LABEL_MSG 10009
#define ID_ADD 10004
#define ID_OPEN 10005
#define ID_BUILD 10006
#define ID_SAVE 10007
#define ID_GAUGE 10008
#define SYMBOL_LISTMAKERDLG_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxSIMPLE_BORDER|wxTAB_TRAVERSAL
#define SYMBOL_LISTMAKERDLG_TITLE _("ListMaker")
#define SYMBOL_LISTMAKERDLG_IDNAME ID_LISTMAKERDLG
#define SYMBOL_LISTMAKERDLG_SIZE wxSize(400, 300)
#define SYMBOL_LISTMAKERDLG_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * ListMakerDlg class declaration
 */

class ListMakerDlg: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( ListMakerDlg )
    DECLARE_EVENT_TABLE()

protected:
	void OpenAFile(wxString &fpath);
	void AddFiles(wxArrayString &files, wxString &path);

public:
    /// Constructors
    ListMakerDlg();
    ListMakerDlg( wxWindow* parent, wxWindowID id = SYMBOL_LISTMAKERDLG_IDNAME, const wxString& caption = SYMBOL_LISTMAKERDLG_TITLE, const wxPoint& pos = SYMBOL_LISTMAKERDLG_POSITION, const wxSize& size = SYMBOL_LISTMAKERDLG_SIZE, long style = SYMBOL_LISTMAKERDLG_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_LISTMAKERDLG_IDNAME, const wxString& caption = SYMBOL_LISTMAKERDLG_TITLE, const wxPoint& pos = SYMBOL_LISTMAKERDLG_POSITION, const wxSize& size = SYMBOL_LISTMAKERDLG_SIZE, long style = SYMBOL_LISTMAKERDLG_STYLE );

    /// Destructor
    ~ListMakerDlg();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin ListMakerDlg event handler declarations

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BROWSER
    void OnBrowserClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_ADD
    void OnAddClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_OPEN
    void OnOpenClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUILD
    void OnBuildClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_SAVE
    void OnSaveClick( wxCommandEvent& event );

////@end ListMakerDlg event handler declarations

////@begin ListMakerDlg member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end ListMakerDlg member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin ListMakerDlg member variables
    wxTextCtrl* m_txtXml;
    wxTextCtrl* m_txtDir;
    wxStaticText* m_labelFile;
////@end ListMakerDlg member variables
};

#endif
    // _LISTMAKERDLG_H_
