/////////////////////////////////////////////////////////////////////////////
// Name:        listmakerframe.h
// Purpose:     
// Author:      xj
// Modified by: 
// Created:     17/11/2010 14:43:19
// RCS-ID:      
// Copyright:   XJ-1
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 17/11/2010 14:43:19

#ifndef _LISTMAKERFRAME_H_
#define _LISTMAKERFRAME_H_


/*!
 * Includes
 */

////@begin includes
#include "wx/frame.h"
#include "wx/statusbr.h"
#include "wx/progdlg.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
class wxStatusBar;
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_LISTMAKERFRAME 10010
#define ID_TEXTCTRL 10011
#define ID_MI_NEW 10014
#define ID_MI_OPEN 10015
#define ID_MI_SAVE 10016
#define ID_MI_SAVEAS 10017
#define ID_MI_EXIT 10019
#define ID_MI_SETDIT 10018
#define ID_MI_ADDFILE 10020
#define ID_MI_BUILD 10021
#define ID_MI_HELP 10022
#define ID_MI_ABOUT 10023
#define ID_MI_LIST 10024
#define ID_MI_SET_ROOT 10025
#define ID_MI_ADD_GROUP 10026
#define ID_MI_ADD_ITEM 10027
#define ID_MI_CALC_NONE 10028
#define ID_MI_CALC_ALL 10029
#define ID_MI_BUILD_LIST 10030
#define ID_STATUSBAR 10013
#define SYMBOL_LISTMAKERFRAME_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxMINIMIZE_BOX|wxMAXIMIZE_BOX|wxCLOSE_BOX
#define SYMBOL_LISTMAKERFRAME_TITLE _("ListMaker")
#define SYMBOL_LISTMAKERFRAME_IDNAME ID_LISTMAKERFRAME
#define SYMBOL_LISTMAKERFRAME_SIZE wxSize(640, 480)
#define SYMBOL_LISTMAKERFRAME_POSITION wxDefaultPosition
////@end control identifiers

class IWxThreadDelegate
{
public:
	virtual void ThreadPro(void *pv) = 0;
};

class WxThreadCls: public wxThread
{
protected:
	IWxThreadDelegate *m_pDelegate;
	void *m_pContext;

public:
	virtual void *Entry()
	{
		if(m_pDelegate)
			m_pDelegate->ThreadPro(m_pContext);

		return 0;
	}

	WxThreadCls(IWxThreadDelegate *pDelegate, void *pContext)
	{
		m_pDelegate = pDelegate;
		m_pContext = pContext;
	}

	virtual ~WxThreadCls(void)
	{

	}
};

/*!
 * ListMakerFrame class declaration
 */

class ListMakerFrame: public wxFrame, public IWxThreadDelegate
{    
    DECLARE_CLASS( ListMakerFrame )
    DECLARE_EVENT_TABLE()

protected:
	WxThreadCls *m_pWxThreadObj;
	bool m_bBuilding;
	bool m_bXmlTxtUpdate;
	bool m_bIsOpenFile;
	bool m_bIsCalcAll;
	wxString m_helpFile;

protected:
	void AddFiles(wxArrayString &files, wxString &path);
	bool SaveToFile(wxString &strXmlDoc, wxString &file);
	bool SaveFile(wxString &file);
	int SaveChange();
	bool IsDoingBuild();
	void StartCalc(bool all);

public:
	void SetHelpFile(wxString &file);
	void OpenAFile(wxString &fpath);
	virtual void ThreadPro(void *pv);

public:
    /// Constructors
    ListMakerFrame();
    ListMakerFrame( wxWindow* parent, wxWindowID id = SYMBOL_LISTMAKERFRAME_IDNAME, const wxString& caption = SYMBOL_LISTMAKERFRAME_TITLE, const wxPoint& pos = SYMBOL_LISTMAKERFRAME_POSITION, const wxSize& size = SYMBOL_LISTMAKERFRAME_SIZE, long style = SYMBOL_LISTMAKERFRAME_STYLE );

    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_LISTMAKERFRAME_IDNAME, const wxString& caption = SYMBOL_LISTMAKERFRAME_TITLE, const wxPoint& pos = SYMBOL_LISTMAKERFRAME_POSITION, const wxSize& size = SYMBOL_LISTMAKERFRAME_SIZE, long style = SYMBOL_LISTMAKERFRAME_STYLE );

    /// Destructor
    ~ListMakerFrame();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin ListMakerFrame event handler declarations

    /// wxEVT_CLOSE_WINDOW event handler for ID_LISTMAKERFRAME
    void OnCloseWindow( wxCloseEvent& event );

    /// wxEVT_COMMAND_MENU_SELECTED event handler for ID_MI_NEW
    void OnMiNewClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_MENU_SELECTED event handler for ID_MI_OPEN
    void OnMiOpenClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_MENU_SELECTED event handler for ID_MI_SAVE
    void OnMiSaveClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_MENU_SELECTED event handler for ID_MI_SAVEAS
    void OnMiSaveasClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_MENU_SELECTED event handler for ID_MI_EXIT
    void OnMiExitClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_MENU_SELECTED event handler for ID_MI_SETDIT
    void OnMiSetditClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_MENU_SELECTED event handler for ID_MI_ADDFILE
    void OnMiAddfileClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_MENU_SELECTED event handler for ID_MI_BUILD
    void OnMiBuildClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_MENU_SELECTED event handler for ID_MI_HELP
    void OnMiHelpClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_MENU_SELECTED event handler for ID_MI_ABOUT
    void OnMiAboutClick( wxCommandEvent& event );

	/// wxEVT_COMMAND_TEXT_UPDATED event handler for ID_TEXTCTRL
	void OnTextctrlTextUpdated( wxCommandEvent& event );

	/// wxEVT_COMMAND_MENU_SELECTED event handler for ID_MI_SET_ROOT
	void OnMiSetRootClick( wxCommandEvent& event );

	/// wxEVT_COMMAND_MENU_SELECTED event handler for ID_MI_ADD_GROUP
	void OnMiAddGroupClick( wxCommandEvent& event );

	/// wxEVT_COMMAND_MENU_SELECTED event handler for ID_MI_ADD_ITEM
	void OnMiAddItemClick( wxCommandEvent& event );

	/// wxEVT_COMMAND_MENU_SELECTED event handler for ID_MI_CALC_NONE
	void OnMiCalcNoneClick( wxCommandEvent& event );

	/// wxEVT_COMMAND_MENU_SELECTED event handler for ID_MI_CALC_ALL
	void OnMiCalcAllClick( wxCommandEvent& event );

	/// wxEVT_COMMAND_MENU_SELECTED event handler for ID_MI_BUILD_LIST
	void OnMiBuildListClick( wxCommandEvent& event );

////@end ListMakerFrame event handler declarations

////@begin ListMakerFrame member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end ListMakerFrame member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin ListMakerFrame member variables
    wxTextCtrl* m_txtXML;
    wxStatusBar* m_statusBar;
////@end ListMakerFrame member variables
};

#endif
    // _LISTMAKERFRAME_H_
