system P00000011
{
    fast_forward                                0.5 0.5
    technique Technique43
    {
        visual_particle_quota                   200
        material                                yanwu1
        renderer                                Billboard
        {
        }
        emitter                                 Box Emitter49
        {
            emission_rate                       12
            angle                               12
            time_to_live                        3.5
            velocity                            60
            box_em_width                        50
            box_em_height                       80
            box_em_depth                        50
        }
        affector                                Colour Affector65
        {
            colour_aff_time_colour              0    1 1 1 0
            colour_aff_time_colour              0.5  1 1 1 0.313726
            colour_aff_time_colour              1    1 1 1 0
        }
        affector                                TextureRotator Affector135
        {
            tex_rot_rotation                    dyn_random
            {
                min                             -3
                max                             3
            }
            tex_rot_speed                       dyn_random
            {
                min                             -1
                max                             1
            }
        }
        affector                                Scale Affector136
        {
            xyz_scale                           dyn_curved_linear
            {
                control_point                   0 60
                control_point                   0.4 50
                control_point                   1 80
            }
        }
    }
}
